terraform-2
Otus-DevOps-2023-05/c3ntik_infra pull request #6
Opened 2023-09-16 04:10 UTC by c3ntik

# Выполнено ДЗ №

 - [ ] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
 - Пункт 1
 - Пункт 2

## Как запустить проект:
 - Например, запустить команду X в директории Y

## Как проверить работоспособность:
 - Например, перейти по ссылке http://localhost:8080

## PR checklist
 - [ ] Выставил label с номером домашнего задания
 - [ ] Выставил label с темой домашнего задания

2023-09-16 04:18 UTC, c3ntik commented
Добрый день!
Снова не пройдет тест?

2023-09-19 14:36 UTC, mrgreyves requested changes
Здравствуйте!)
Рекомендую свериться с результатами тестов
У вас нехватает некоторых файлов

2023-09-20 02:10 UTC, c3ntik commented
спасибо, добавил файлы, но тест не проходит)

2023-09-23 10:27 UTC, mrgreyves approved these changes
Здарвствуйте!)
Тут особенность определения провайдера
Ничего страшного =)

2023-10-05 07:59 UTC, merged